import type { Metadata } from "next";
import "./globals.css";
import { Geologica, Varela_Round } from "next/font/google";
import AppProvider from "@/src/app/providers/provider";
import { cn } from "@/src/shared/cn/lib/utils";
import { isWebView } from "@/src/shared/lib/utils";

const geologica = Geologica({
  subsets: ["latin", "cyrillic"],
  variable: "--font-geologica",
  display: "swap",
});

const valera_round = Varela_Round({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-digits",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning translate="no">
      <body
        className={cn(
          geologica.className,
          valera_round.variable,
          "antialiased",
          isWebView && "h-screen overflow-hidden"
        )}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
